apiVersion: apps/v1
kind: Deployment
metadata:
  name: biblioteca-frontend-deployment
  namespace: biblioteca-frontend
spec:
  selector:
    matchLabels:
      app: biblioteca-frontend-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: biblioteca-frontend-deployment
    spec:
      containers:
        - name: biblioteca-frontend-container
          image: gitlab.reto-ucu.net:5050/ucudal/reto-2023/diciembre/biblioteca/frontend:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "100Mi"
              cpu: "100m"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: biblioteca-frontend-secrets

