apiVersion: v1
kind: Service
metadata:
  name: biblioteca-frontend-service
  namespace: biblioteca-frontend
spec:
  selector:
    app: biblioteca-frontend-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
